In [1]:
import  torch
torch.cuda.device_count()

1

In [50]:
# %load finetune_textcnn.py
#!/usr/bin/env python
"""
FileName: finetune.py
Description:
Author: Stark Lv
Date: 2021/2/27 6:13 PM
Version: 0.1
"""

from transformers import get_linear_schedule_with_warmup
from TEXTCNN_pytorch import TEXTCNN
import torch
import logging
from torch import nn
from Data_generator_vocab import Corpus
import time
import datetime
from tqdm import tqdm
import numpy as np
import torch.nn.functional as F
import os
import json
import pandas as pd
from sklearn.metrics import roc_auc_score


def format_time(elapsed):
    elapsed_rounded = int(round(elapsed))
    return str(datetime.timedelta(seconds = elapsed_rounded))

class fintune():

    def __init__(self, model, corpus):

        self.set_device() #创建了self.device, self.n_gpu
        self.set_random_seed() #设置随机数种子,保证所有结果可以复现

        # 加载训练集、验证集、测试集
        print(f"{'加载训练集、验证集、测试集 Loading':*^80}")
        self.train_loader, self.valid_loader, self.test_loader = corpus.get_loaders()

        #加载model
        #self.model, self.tokenizer = self.load_model_tokenizer(model_name)


        self.model = model
        
        # move model to GPU
        if self.n_gpu > 1:
            device_ids = [0, 1, 2, 3]
            self.model =torch.nn.DataParallel(self.model, device_ids= device_ids)
        self.model = self.model.to(self.device)

        #loss function & optimizer
        # 带权重的损失函数, 若positive_label为1的f1_score为 0.75，positive_label为0的f1_score为0.85
        #self.loss_func = nn.CrossEntropyLoss(weight= torch.tensor([1.1765, 1.3333])).to(self.device)
        self.loss_func = nn.CrossEntropyLoss(weight=torch.tensor([0.5, 0.5])).to(self.device)
        self.optimizer = torch.optim.Adam(
                self.model.parameters(),
                lr = HYPERS["LR"],
                eps = 1e-8)




    """
    def load_model_tokenizer(self, model_name):
        #model_path = os.path.join(os.getcwd(), MODELS[model_name]["path"])
        model_path = MODELS[model_name]["path"]
        assert model_name in MODELS

        if self.retrain_model_path is None:

            print(f"### 从 {model_path} 加载预训练模型, 重新训练 ###")
            model = MODELS[model_name]["class"](model_path)
        else:
            print(f"{'加载已预训练好的模型,继续训练':*^80}")
            model = torch.load("./fintuned_model/" + self.retrain_model_path)

        print(f"## Model {self.model_name} loaded. ##")

        tokenizer = MODELS[model_name]["tokenizer"].from_pretrained(model_path)

        ## __class__.__name__输出类的名字
        print(f"## Tokenizer {tokenizer.__class__.__name__} loaded. ##")

        return model, tokenizer
    """
    
    def set_random_seed(self):
        # Set the seed value all over the place to make this reproducible.
        self.seed_val = 2021
        np.random.seed(self.seed_val)
        torch.manual_seed(self.seed_val)

    def set_device(self):
        ###设置日志时间的输出格式,说明在那段时间用过GPU
        LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
        DATE_FORMAT = "%m/%d/%Y %H:%M:%S %p"
        logging.basicConfig(filename='NLP_GPU.log', level=logging.DEBUG, format=LOG_FORMAT, datefmt=DATE_FORMAT)

        # 设置运行环境GPU
        self.device = torch.device("cuda:0")
        self.n_gpu = torch.cuda.device_count()
        logging.info(msg = f"\n Using GPU, {self.n_gpu} device available")

    def run_epoch(self):

        #list to store a number of quantities such as
        #training and validation loss, validation accuracy, and timings.
        training_stats = []


        #Total number of training steps is [number of batches × number of epochs]
        total_steps = len(self.train_loader) * HYPERS["EPOCHS"]
        # create the learning rate scheduler
        self.scheduler = get_linear_schedule_with_warmup(
            self.optimizer, num_warmup_steps = 100, num_training_steps = total_steps
        )

        total_t0 = time.time()

        print(f"### Trainng {HYPERS['EPOCHS']} EPOCHS start ###")
        for epoch in tqdm(range(1, HYPERS["EPOCHS"] + 1), unit = "epoch",
                          desc = f"Training All {HYPERS['EPOCHS']} Epochs"):
            # Measure how long the per training epoch takes
            t0 = time.time()

            # Put the model into training model
            print(f"### EPOCH {epoch} train  start")
            self.model.train()

            epoch_train_loss = self.train(epoch)
            # measure avg batch loss in specific epoch
            avg_train_loss = epoch_train_loss / len(self.train_loader)
            # Measure how long this epoch took.
            training_time = format_time(time.time() - t0)
            print(f"## per batch train loss for epoch {epoch} is {avg_train_loss} ",
                  f"total train time : {training_time}")

            t0 = time.time()

            # eval mode
            # 在eval模式下不会应用DROPOUT和BATCHNORM
            print(f"### EPOCH {epoch} val start")
            self.model.eval()

            epoch_eval_loss, eval_auc = self.eval(metric=roc_auc_score)
            avg_eval_loss = epoch_eval_loss / len(self.valid_loader)
            validation_time = format_time(time.time() - t0)
            print(f"## per batch valid loss for epoch {epoch} is {avg_eval_loss} ",
                  f"total valid time : {validation_time}, Validation auc score {eval_auc}")

            # Record all statistics from this epoch.
            training_stats.append(
                {
                    'Epoch': epoch,
                    'Train Loss': epoch_train_loss,
                    'Avg Train Loss': avg_train_loss,
                    'Train Time': training_time,
                    'Valid Loss': epoch_eval_loss,
                    'Avg Valid Loss': avg_eval_loss,
                    'Valid Time': validation_time,
                    'Valid AUC': eval_auc,
                    'Test Results Dir': 'Model{}_BATCH{}_LR{}/'.format(self.model_name,
                     HYPERS['BATCH_SIZE'], HYPERS['LR'])
                }
            )

        test_t0 = time.time()
        self.test()
        print("Test Time Consume {}".format(format_time(time.time() - test_t0)))
        self.save_stats(training_stats)
        print(f"{'Training complete !':*^80}")
        print(f"### Total Process took {format_time(time.time() - total_t0)} ####")


    def train(self, epoch):
        total_train_loss = 0

        for batch in tqdm(self.train_loader, desc=f"Epoch {epoch}>>>>train", unit="batch"):
            # input_ids, attention_mask, token_type_id和Label混在一起
            inputs = [data.to(self.device) for data in batch[:-1]]
            labels = batch[-1].to(self.device)
            outputs = self.model(*inputs)


            batch_loss = self.loss_func(outputs, labels)
            total_train_loss += batch_loss.to("cpu").data.numpy()
            # clear any previously calculated gradients before performing a backward pass.
            self.optimizer.zero_grad()

            # perform a backward pass to calculate the gradients
            batch_loss.backward()

            # normalization of the gradients to 1.0 to avoid exploding gradients
            nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)

            # update parameters and take a step using the computed gradient
            self.optimizer.step()

            #update the learning rate 
            self.scheduler.step()

            #print(f"per batch loss {batch_loss.to('cpu').data.numpy()}")

        return total_train_loss

    def eval(self, metric):
        total_eval_loss = 0
        predicted_scores = np.array([])
        target_labels = np.array([])
        #predicted_labels = np.array([])

        for batch in self.valid_loader:
            inputs = [data.to(self.device) for data in batch[:-1]]
            labels = batch[-1].to(self.device)

            # Tell pytorch not to bother with constructing the compute graph during
            # the forward pass, since this is only needed for backprop (training).
            with torch.no_grad():
                outputs = self.model(*inputs)
                loss = self.loss_func(outputs, labels)
                total_eval_loss += loss.to("cpu").data.numpy()

                # move logits and labels to CPU,存储在CPU上面的变量不能和存储在GPU上面的变量进行运算
                logits = F.softmax(outputs.to("cpu"), dim = 1).data.numpy()
                label_ids = labels.to("cpu").data.numpy()
                y_pred = logits[:, 1]
                #y_pred1 = np.argmax(logits, axis = 1)
                predicted_scores = np.append(predicted_scores, y_pred)
                #predicted_labels = np.append(predicted_labels, y_pred1)
                target_labels = np.append(target_labels, label_ids)


        task_auc = metric(target_labels, predicted_scores)

        #print(f"{'classification_report':*^80}")
        #print(classification_report(target_labels, predicted_labels))
        return total_eval_loss , task_auc

    def test(self):

        prediction_scores = np.array([])
        print(f"{'Predict task':*^80}")
        for batch in tqdm(self.test_loader, desc = "Predict Scores Loading", unit = "batch"):
            inputs = [data.to(self.device) for data in batch]

            with torch.no_grad():
                outputs = self.model(*inputs)
                logits = F.softmax(outputs.to("cpu"), dim=1).data.numpy()
                y_pred = logits[:, 1]
                prediction_scores = np.append(prediction_scores, y_pred)

        self.save_predictions(prediction_scores)

    def save_predictions(self, predicts):
        file_path = "./finetuned_results/" + 'Model{}_BATCH{}_EPOCH{}_LR{}/'.format(self.model_name,
                  HYPERS['BATCH_SIZE'],HYPERS['EPOCHS'], HYPERS['LR'])
        if not os.path.exists(file_path):
            os.mkdir(file_path)

        #输出当前时间
        dt = str(datetime.datetime.now()).split(" ")[0]
        filename = "{}_{}_(对应id和score).json".format(self.model_name, dt)
        with open(file_path + filename, "w") as fw:
            for idx, predict in enumerate(predicts):
                predict = {"id": idx, "label": predict}
                json.dump(predict, fw)
                if idx == len(predicts) - 1:
                    break
                fw.write("\n")

        filename2 = "{}_{}_result.tsv".format(self.model_name, dt)
        with open(file_path + filename2, "w") as fw:
            for idx, predict in enumerate(predicts):
                fw.write(str(predict))
                if idx == len(predicts) - 1:
                    break
                fw.write("\n")

    def save_stats(self ,stats):
        df = pd.DataFrame(stats)
        filename = 'Stats_{}_BATCH{}_Epoch{}_LR{}.csv'.format(self.model_name, HYPERS['BATCH_SIZE'],
                            HYPERS['EPOCHS'], HYPERS['LR'])
        df.to_csv("./finetuned_results/" + filename, sep = ",", encoding="utf-8", index = False)

    def save_model(self):
        # 保存训练好的模型
        model_name = 'Model{}_BATCH{}_Epoch{}_LR{}_TIME{}.pkl'.format(self.model_name, HYPERS['BATCH_SIZE'],
        HYPERS['EPOCHS'], HYPERS['LR'],time.strftime("%Y_%m_%d_%H_%M",time.localtime()))
        torch.save(self.model, "./finetuned_model/" + model_name)
        print("Fintuned model saved")


if __name__ == "__main__":
    ## 使用编号为4,5的两张显卡
    #os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
    #os.environ["CUDA_VISIBLE_DEVICES"] = "4, 5, 6, 7"
    # global hyper parameters
    HYPERS = {
        "BATCH_SIZE":4,
        "LR": 5e-5,
        "EPOCHS": 7,
    }
    seed_val = 2021
    corpus = Corpus(HYPERS["BATCH_SIZE"], seed_val)
    class_num = 2
    maxlen = corpus.max_len
    max_features = len(corpus.vocab)
    embedding_dims = 300
    batch_size = 4
    dropout_rate = 0.2
    feature_size = 128
    kernel_sizes = [2, 3, 4, 5]

    print("Build model.....")
    model = TEXTCNN(maxlen=maxlen,
                    max_features=max_features,
                    embedding_dims=embedding_dims,
                    class_num=class_num,
                    kernel_sizes=kernel_sizes,
                    dropout_rate=dropout_rate,
                    feature_size=feature_size)
    corpus = Corpus(HYPERS["BATCH_SIZE"], seed_val)
    app = fintune(model, corpus)
    app.run_epoch()
    #app.save_model()

********************************Data_precessing*********************************
## dataset size is 121105
*******************************Load  dataset ....*******************************
## Load Datasets Consume 0:00:11 s ###
************************All Train and Test Data loaded !************************
Build model.....
********************************Data_precessing*********************************
## dataset size is 121105
*******************************Load  dataset ....*******************************
## Load Datasets Consume 0:00:09 s ###
************************All Train and Test Data loaded !************************


Epoch 1>>>>train:   0%|                                                                   | 0/27249 [00:00<?, ?batch/s]

*****************************加载训练集、验证集、测试集 Loading******************************
### Trainng 7 EPOCHS start ###
### EPOCH 1 train  start



Epoch 1>>>>train:   1%|▊                                                        | 393/27249 [00:16<18:20, 24.40batch/s]


Training All 7 Epochs:   0%|                                                                  | 0/7 [00:16<?, ?epoch/s]


KeyboardInterrupt: 

In [31]:
model

TEXTCNN(
  (embedding): Embedding(20604, 300)
  (relu): ReLU()
  (dropout): Dropout(p=0.2)
  (classifier): Linear(in_features=512, out_features=2, bias=True)
)

In [5]:
app.train_loader

In [6]:
model

TEXTCNN(
  (embedding): Embedding(20604, 300)
  (relu): ReLU()
  (dropout): Dropout(p=0.2)
  (classifier): Linear(in_features=512, out_features=2, bias=True)
)

In [9]:
for batch in app.train_loader:
    inputs = [data for data in batch[:-1]]
    labels = batch[-1]
    break

In [10]:
labels

tensor([0, 1, 1, 1])

In [30]:
inputs.dtype

torch.int64

In [44]:
from imp import reload
import TEXTCNN_pytorch
reload(TEXTCNN_pytorch)
from TEXTCNN_pytorch import TEXTCNN

In [45]:
class_num = 2
maxlen = corpus.max_len
max_features = len(corpus.vocab)
embedding_dims = 300
batch_size = 32
dropout_rate = 0.2
feature_size = 128
kernel_sizes = [2, 3, 4, 5]

print("Build model.....")
model = TEXTCNN(maxlen=maxlen,
                    max_features=max_features,
                    embedding_dims=embedding_dims,
                    class_num=class_num,
                    kernel_sizes=kernel_sizes,
                    dropout_rate=dropout_rate,
                    feature_size=feature_size)

Build model.....


In [4]:
inputs

NameError: name 'inputs' is not defined

In [47]:
model = model.to(app.device)

In [48]:
model

TEXTCNN(
  (embedding): Embedding(20604, 300)
  (conv1ds): ModuleList(
    (0): Conv1d(300, 128, kernel_size=(2,), stride=(1,))
    (1): Conv1d(300, 128, kernel_size=(3,), stride=(1,))
    (2): Conv1d(300, 128, kernel_size=(4,), stride=(1,))
    (3): Conv1d(300, 128, kernel_size=(5,), stride=(1,))
  )
  (relu): ReLU()
  (avgpools): ModuleList(
    (0): MaxPool1d(kernel_size=92, stride=92, padding=0, dilation=1, ceil_mode=False)
    (1): MaxPool1d(kernel_size=91, stride=91, padding=0, dilation=1, ceil_mode=False)
    (2): MaxPool1d(kernel_size=90, stride=90, padding=0, dilation=1, ceil_mode=False)
    (3): MaxPool1d(kernel_size=89, stride=89, padding=0, dilation=1, ceil_mode=False)
  )
  (dropout): Dropout(p=0.2)
  (classifier): Linear(in_features=512, out_features=2, bias=True)
)

In [38]:
inputs = inputs.to(app.device)

In [49]:
model(inputs)

tensor([[-0.5557,  0.0486],
        [-0.0607, -0.2917],
        [-0.4231, -0.6306],
        [-0.2986,  0.6190]], device='cuda:0', grad_fn=<AddmmBackward>)

In [40]:
inputs.device

device(type='cuda', index=0)

In [41]:
next(model.parameters()).device

device(type='cuda', index=0)

In [42]:
model

TEXTCNN(
  (embedding): Embedding(20604, 300)
  (relu): ReLU()
  (dropout): Dropout(p=0.2)
  (classifier): Linear(in_features=512, out_features=2, bias=True)
)

In [43]:
for param in model.parameters():
    print(type(param.data), param.size())


<class 'torch.Tensor'> torch.Size([20604, 300])
<class 'torch.Tensor'> torch.Size([2, 512])
<class 'torch.Tensor'> torch.Size([2])


In [51]:
import tarfile 
import os

tar = tarfile.open("textcnn.tar.gz", "w:gz")

for root, dir, files in os.walk("./code"):
    for file in files:
        fullpath = os.path.join(root, file)
        tar.add(fullpath)

tar.close()

In [2]:
m = 4
n = 3

In [3]:
[[1 for _ in range(m)] for _ in range(n)]

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]

In [5]:
"@ . . .".split()

['@', '.', '.', '.']

In [6]:
import torch
inputs = torch.rand(2, 3, 5)

In [8]:
new_inputs = inputs.new()

In [9]:
inputs.new().resize_()

tensor([])

In [10]:
inputs.dim()

3

In [16]:
from itertools import repeat

In [14]:
list(itertools.repeat(1, 1))

[1]

In [21]:
inputs2 = inputs.new().resize_(inputs.size(0), *repeat(1, inputs.dim() - 2), inputs.size(2))

TypeError: resize_(): argument 'size' must be tuple of ints, but found element of type itertools.repeat at pos 2

In [27]:
inputs2.fill_(0)

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])

In [23]:
repeat(1, inputs.dim() - 2)

repeat(1, 1)

In [24]:
inputs.clone()

tensor([[[0.7501, 0.8988, 0.8986, 0.4217, 0.5892],
         [0.0373, 0.2572, 0.5352, 0.1509, 0.4278],
         [0.2676, 0.8277, 0.5438, 0.8423, 0.3216]],

        [[0.9667, 0.2692, 0.7169, 0.9250, 0.8498],
         [0.4199, 0.4934, 0.1143, 0.0123, 0.6788],
         [0.5399, 0.2404, 0.2149, 0.6032, 0.8619]]])

In [25]:
inputs

tensor([[[0.7501, 0.8988, 0.8986, 0.4217, 0.5892],
         [0.0373, 0.2572, 0.5352, 0.1509, 0.4278],
         [0.2676, 0.8277, 0.5438, 0.8423, 0.3216]],

        [[0.9667, 0.2692, 0.7169, 0.9250, 0.8498],
         [0.4199, 0.4934, 0.1143, 0.0123, 0.6788],
         [0.5399, 0.2404, 0.2149, 0.6032, 0.8619]]])

In [28]:
noise = inputs2.clone()

In [39]:
drop_prob = 0.2

In [40]:
noise.bernoulli_(1 - drop_prob).div_(1 - drop_prob)

tensor([[[1.2500, 1.2500, 1.2500, 1.2500, 0.0000]],

        [[1.2500, 1.2500, 1.2500, 1.2500, 1.2500]]])

In [41]:
noise

tensor([[[1.2500, 1.2500, 1.2500, 1.2500, 0.0000]],

        [[1.2500, 1.2500, 1.2500, 1.2500, 1.2500]]])

In [44]:
inputs.size()

torch.Size([2, 3, 5])

In [53]:
noise = noise.expand_as(inputs)

In [49]:
inputs3 = inputs.clone()

In [58]:
inputs3.mul_(noise)

tensor([[[0.9376, 1.1235, 1.1232, 0.5271, 0.0000],
         [0.0467, 0.3215, 0.6690, 0.1886, 0.0000],
         [0.3346, 1.0346, 0.6798, 1.0529, 0.0000]],

        [[1.2084, 0.3365, 0.8962, 1.1562, 1.0623],
         [0.5248, 0.6167, 0.1428, 0.0153, 0.8485],
         [0.6749, 0.3006, 0.2686, 0.7540, 1.0774]]])

In [60]:
inputs3

tensor([[[0.9376, 1.1235, 1.1232, 0.5271, 0.0000],
         [0.0467, 0.3215, 0.6690, 0.1886, 0.0000],
         [0.3346, 1.0346, 0.6798, 1.0529, 0.0000]],

        [[1.2084, 0.3365, 0.8962, 1.1562, 1.0623],
         [0.5248, 0.6167, 0.1428, 0.0153, 0.8485],
         [0.6749, 0.3006, 0.2686, 0.7540, 1.0774]]])

In [61]:
inputs

tensor([[[0.7501, 0.8988, 0.8986, 0.4217, 0.5892],
         [0.0373, 0.2572, 0.5352, 0.1509, 0.4278],
         [0.2676, 0.8277, 0.5438, 0.8423, 0.3216]],

        [[0.9667, 0.2692, 0.7169, 0.9250, 0.8498],
         [0.4199, 0.4934, 0.1143, 0.0123, 0.6788],
         [0.5399, 0.2404, 0.2149, 0.6032, 0.8619]]])

In [62]:
noise

tensor([[[1.2500, 1.2500, 1.2500, 1.2500, 0.0000],
         [1.2500, 1.2500, 1.2500, 1.2500, 0.0000],
         [1.2500, 1.2500, 1.2500, 1.2500, 0.0000]],

        [[1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
         [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
         [1.2500, 1.2500, 1.2500, 1.2500, 1.2500]]])

In [1]:
from TEXTCNN_pytorch import TEXTCNN

ImportError: cannot import name 'Spatial_Dropout' from 'Spatial_Dropout' (E:\lv_python\NLP\阿里天池小布助手\TEXTCNN\code\Spatial_Dropout.py)

In [2]:
from Spatial_Dropout import SpatialDropout

In [ ]:
import torch

In [64]:
# %load finetune_textcnn.py
#!/usr/bin/env python
"""
FileName: finetune.py
Description:
Author: Stark Lv
Date: 2021/2/27 6:13 PM
Version: 0.1
"""

from transformers import get_linear_schedule_with_warmup
from TEXTCNN_pytorch import TEXTCNN
import torch
import logging
from torch import nn
from Data_generator_vocab import Corpus
import time
import datetime
from tqdm import tqdm
import numpy as np
import torch.nn.functional as F
import os
import json
import pandas as pd
from sklearn.metrics import roc_auc_score


def format_time(elapsed):
    elapsed_rounded = int(round(elapsed))
    return str(datetime.timedelta(seconds = elapsed_rounded))

class fintune():

    def __init__(self, model, corpus):

        self.set_device() #创建了self.device, self.n_gpu
        self.set_random_seed() #设置随机数种子,保证所有结果可以复现

        # 加载训练集、验证集、测试集
        print(f"{'加载训练集、验证集、测试集 Loading':*^80}")
        self.train_loader, self.valid_loader, self.test_loader = corpus.get_loaders()

        #加载model
        #self.model, self.tokenizer = self.load_model_tokenizer(model_name)


        self.model = model
        
        # move model to GPU
        if self.n_gpu > 1:
            device_ids = [0, 1, 2, 3]
            self.model =torch.nn.DataParallel(self.model, device_ids= device_ids)
        self.model = self.model.to(self.device)

        #loss function & optimizer
        # 带权重的损失函数, 若positive_label为1的f1_score为 0.75，positive_label为0的f1_score为0.85
        #self.loss_func = nn.CrossEntropyLoss(weight= torch.tensor([1.1765, 1.3333])).to(self.device)
        self.loss_func = nn.CrossEntropyLoss(weight=torch.tensor([0.5, 0.5])).to(self.device)
        self.optimizer = torch.optim.Adam(
                self.model.parameters(),
                lr = HYPERS["LR"],
                eps = 1e-8)




    """
    def load_model_tokenizer(self, model_name):
        #model_path = os.path.join(os.getcwd(), MODELS[model_name]["path"])
        model_path = MODELS[model_name]["path"]
        assert model_name in MODELS

        if self.retrain_model_path is None:

            print(f"### 从 {model_path} 加载预训练模型, 重新训练 ###")
            model = MODELS[model_name]["class"](model_path)
        else:
            print(f"{'加载已预训练好的模型,继续训练':*^80}")
            model = torch.load("./fintuned_model/" + self.retrain_model_path)

        print(f"## Model {self.model_name} loaded. ##")

        tokenizer = MODELS[model_name]["tokenizer"].from_pretrained(model_path)

        ## __class__.__name__输出类的名字
        print(f"## Tokenizer {tokenizer.__class__.__name__} loaded. ##")

        return model, tokenizer
    """
    
    def set_random_seed(self):
        # Set the seed value all over the place to make this reproducible.
        self.seed_val = 2021
        np.random.seed(self.seed_val)
        torch.manual_seed(self.seed_val)

    def set_device(self):
        ###设置日志时间的输出格式,说明在那段时间用过GPU
        LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
        DATE_FORMAT = "%m/%d/%Y %H:%M:%S %p"
        logging.basicConfig(filename='NLP_GPU.log', level=logging.DEBUG, format=LOG_FORMAT, datefmt=DATE_FORMAT)

        # 设置运行环境GPU
        self.device = torch.device("cuda:0")
        self.n_gpu = torch.cuda.device_count()
        logging.info(msg = f"\n Using GPU, {self.n_gpu} device available")

    def run_epoch(self):

        #list to store a number of quantities such as
        #training and validation loss, validation accuracy, and timings.
        training_stats = []


        #Total number of training steps is [number of batches × number of epochs]
        total_steps = len(self.train_loader) * HYPERS["EPOCHS"]
        # create the learning rate scheduler
        self.scheduler = get_linear_schedule_with_warmup(
            self.optimizer, num_warmup_steps = 100, num_training_steps = total_steps
        )

        total_t0 = time.time()

        print(f"### Trainng {HYPERS['EPOCHS']} EPOCHS start ###")
        for epoch in tqdm(range(1, HYPERS["EPOCHS"] + 1), unit = "epoch",
                          desc = f"Training All {HYPERS['EPOCHS']} Epochs"):
            # Measure how long the per training epoch takes
            t0 = time.time()

            # Put the model into training model
            print(f"### EPOCH {epoch} train  start")
            self.model.train()

            epoch_train_loss = self.train(epoch)
            # measure avg batch loss in specific epoch
            avg_train_loss = epoch_train_loss / len(self.train_loader)
            # Measure how long this epoch took.
            training_time = format_time(time.time() - t0)
            print(f"## per batch train loss for epoch {epoch} is {avg_train_loss} ",
                  f"total train time : {training_time}")

            t0 = time.time()

            # eval mode
            # 在eval模式下不会应用DROPOUT和BATCHNORM
            print(f"### EPOCH {epoch} val start")
            self.model.eval()

            epoch_eval_loss, eval_auc = self.eval(metric=roc_auc_score)
            avg_eval_loss = epoch_eval_loss / len(self.valid_loader)
            validation_time = format_time(time.time() - t0)
            print(f"## per batch valid loss for epoch {epoch} is {avg_eval_loss} ",
                  f"total valid time : {validation_time}, Validation auc score {eval_auc}")

            # Record all statistics from this epoch.
            training_stats.append(
                {
                    'Epoch': epoch,
                    'Train Loss': epoch_train_loss,
                    'Avg Train Loss': avg_train_loss,
                    'Train Time': training_time,
                    'Valid Loss': epoch_eval_loss,
                    'Avg Valid Loss': avg_eval_loss,
                    'Valid Time': validation_time,
                    'Valid AUC': eval_auc,
                    'Test Results Dir': 'Model{}_BATCH{}_LR{}/'.format(self.model_name,
                     HYPERS['BATCH_SIZE'], HYPERS['LR'])
                }
            )

        test_t0 = time.time()
        self.test()
        print("Test Time Consume {}".format(format_time(time.time() - test_t0)))
        self.save_stats(training_stats)
        print(f"{'Training complete !':*^80}")
        print(f"### Total Process took {format_time(time.time() - total_t0)} ####")


    def train(self, epoch):
        total_train_loss = 0

        for batch in tqdm(self.train_loader, desc=f"Epoch {epoch}>>>>train", unit="batch"):
            # input_ids, attention_mask, token_type_id和Label混在一起
            inputs = [data.to(self.device) for data in batch[:-1]]
            labels = batch[-1].to(self.device)
            outputs = self.model(*inputs)


            batch_loss = self.loss_func(outputs, labels)
            total_train_loss += batch_loss.to("cpu").data.numpy()
            # clear any previously calculated gradients before performing a backward pass.
            self.optimizer.zero_grad()

            # perform a backward pass to calculate the gradients
            batch_loss.backward()

            # normalization of the gradients to 1.0 to avoid exploding gradients
            nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)

            # update parameters and take a step using the computed gradient
            self.optimizer.step()

            #update the learning rate 
            self.scheduler.step()

            #print(f"per batch loss {batch_loss.to('cpu').data.numpy()}")

        return total_train_loss

    def eval(self, metric):
        total_eval_loss = 0
        predicted_scores = np.array([])
        target_labels = np.array([])
        #predicted_labels = np.array([])

        for batch in self.valid_loader:
            inputs = [data.to(self.device) for data in batch[:-1]]
            labels = batch[-1].to(self.device)

            # Tell pytorch not to bother with constructing the compute graph during
            # the forward pass, since this is only needed for backprop (training).
            with torch.no_grad():
                outputs = self.model(*inputs)
                loss = self.loss_func(outputs, labels)
                total_eval_loss += loss.to("cpu").data.numpy()

                # move logits and labels to CPU,存储在CPU上面的变量不能和存储在GPU上面的变量进行运算
                logits = F.softmax(outputs.to("cpu"), dim = 1).data.numpy()
                label_ids = labels.to("cpu").data.numpy()
                y_pred = logits[:, 1]
                #y_pred1 = np.argmax(logits, axis = 1)
                predicted_scores = np.append(predicted_scores, y_pred)
                #predicted_labels = np.append(predicted_labels, y_pred1)
                target_labels = np.append(target_labels, label_ids)


        task_auc = metric(target_labels, predicted_scores)

        #print(f"{'classification_report':*^80}")
        #print(classification_report(target_labels, predicted_labels))
        return total_eval_loss , task_auc

    def test(self):

        prediction_scores = np.array([])
        print(f"{'Predict task':*^80}")
        for batch in tqdm(self.test_loader, desc = "Predict Scores Loading", unit = "batch"):
            inputs = [data.to(self.device) for data in batch]

            with torch.no_grad():
                outputs = self.model(*inputs)
                logits = F.softmax(outputs.to("cpu"), dim=1).data.numpy()
                y_pred = logits[:, 1]
                prediction_scores = np.append(prediction_scores, y_pred)

        self.save_predictions(prediction_scores)

    def save_predictions(self, predicts):
        file_path = "./finetuned_results/" + 'Model{}_BATCH{}_EPOCH{}_LR{}/'.format(self.model_name,
                  HYPERS['BATCH_SIZE'],HYPERS['EPOCHS'], HYPERS['LR'])
        if not os.path.exists(file_path):
            os.mkdir(file_path)

        #输出当前时间
        dt = str(datetime.datetime.now()).split(" ")[0]
        filename = "{}_{}_(对应id和score).json".format(self.model_name, dt)
        with open(file_path + filename, "w") as fw:
            for idx, predict in enumerate(predicts):
                predict = {"id": idx, "label": predict}
                json.dump(predict, fw)
                if idx == len(predicts) - 1:
                    break
                fw.write("\n")

        filename2 = "{}_{}_result.tsv".format(self.model_name, dt)
        with open(file_path + filename2, "w") as fw:
            for idx, predict in enumerate(predicts):
                fw.write(str(predict))
                if idx == len(predicts) - 1:
                    break
                fw.write("\n")

    def save_stats(self ,stats):
        df = pd.DataFrame(stats)
        filename = 'Stats_{}_BATCH{}_Epoch{}_LR{}.csv'.format(self.model_name, HYPERS['BATCH_SIZE'],
                            HYPERS['EPOCHS'], HYPERS['LR'])
        df.to_csv("./finetuned_results/" + filename, sep = ",", encoding="utf-8", index = False)

    def save_model(self):
        # 保存训练好的模型
        model_name = 'Model{}_BATCH{}_Epoch{}_LR{}_TIME{}.pkl'.format(self.model_name, HYPERS['BATCH_SIZE'],
        HYPERS['EPOCHS'], HYPERS['LR'],time.strftime("%Y_%m_%d_%H_%M",time.localtime()))
        torch.save(self.model, "./finetuned_model/" + model_name)
        print("Fintuned model saved")


if __name__ == "__main__":
    ## 使用编号为4,5的两张显卡
    #os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
    #os.environ["CUDA_VISIBLE_DEVICES"] = "4, 5, 6, 7"
    # global hyper parameters
    HYPERS = {
        "BATCH_SIZE":32 * 4,
        "LR": 5e-5,
        "EPOCHS": 7,
    }
    seed_val = 2021
    corpus = Corpus(HYPERS["BATCH_SIZE"], seed_val)
    class_num = 2
    maxlen = corpus.max_len
    max_features = len(corpus.vocab)
    embedding_dims = 400
    batch_size = 4
    dropout_rate = 0.2
    feature_size = 1024
    kernel_sizes = [2, 3, 4, 5]

    print("Build model.....")
    model = TEXTCNN(maxlen=maxlen,
                    max_features=max_features,
                    embedding_dims=embedding_dims,
                    class_num=class_num,
                    kernel_sizes=kernel_sizes,
                    dropout_rate=dropout_rate,
                    feature_size=feature_size)
    corpus = Corpus(HYPERS["BATCH_SIZE"], seed_val)
    app = fintune(model, corpus)
    #app.run_epoch()
    #app.save_model()

********************************Data_precessing*********************************
## dataset size is 121105
*******************************Load  dataset ....*******************************
## Load Datasets Consume 0:00:07 s ###
************************All Train and Test Data loaded !************************
Build model.....
********************************Data_precessing*********************************
## dataset size is 121105
*******************************Load  dataset ....*******************************
## Load Datasets Consume 0:00:07 s ###
************************All Train and Test Data loaded !************************
*****************************加载训练集、验证集、测试集 Loading******************************


In [90]:
for batch in app.train_loader:
    inputs = batch[:-1]
    labels = batch[-1]
    break

In [135]:

import TEXTCNN_pytorch
reload(TEXTCNN_pytorch)
from TEXTCNN_pytorch import TEXTCNN

In [91]:
inputs = [inputs[0][:4]]

In [136]:
model = TEXTCNN(maxlen=maxlen,
                    max_features=max_features,
                    embedding_dims=embedding_dims,
                    class_num=class_num,
                    kernel_sizes=kernel_sizes,
                    dropout_rate=dropout_rate,
                    feature_size=feature_size)

In [137]:
model(*inputs)

tensor([[0.5152, 0.4848],
        [0.4941, 0.5059],
        [0.5498, 0.4502],
        [0.5403, 0.4597]], grad_fn=<SoftmaxBackward>)

In [134]:
inputs

[tensor([[    2,   152,  3502,     9,   149, 10705,    54,   716,    28,   109,
            110,    72,     3,   947,  2257,   760,   906, 14553,    58,    93,
            110,     3,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0],
         [    2,    10,     7,    48,    21,     3,    23,   236,   198,     3,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        

In [130]:
inputs[0].size()

torch.Size([4, 93])

In [140]:
x = [torch.rand(2, 3)]
def change(x):
    print(x)
    print(type(x))
    return x

In [141]:
change(*x)

tensor([[0.9661, 0.0943, 0.9204],
        [0.5622, 0.1390, 0.7411]])
<class 'torch.Tensor'>


tensor([[0.9661, 0.0943, 0.9204],
        [0.5622, 0.1390, 0.7411]])

In [2]:
# %load finetune_textcnn.py
#!/usr/bin/env python
"""
FileName: finetune.py
Description:
Author: Stark Lv
Date: 2021/2/27 6:13 PM
Version: 0.1
"""

from transformers import get_linear_schedule_with_warmup
from TEXTCNN_pytorch import TEXTCNN
import torch
import logging
from torch import nn
from Data_generator_vocab import Corpus
import time
import datetime
from tqdm import tqdm
import numpy as np
import torch.nn.functional as F
import os
import json
import pandas as pd
from sklearn.metrics import roc_auc_score


def format_time(elapsed):
    elapsed_rounded = int(round(elapsed))
    return str(datetime.timedelta(seconds = elapsed_rounded))

class fintune():

    def __init__(self, model, corpus):

        self.set_device() #创建了self.device, self.n_gpu
        self.set_random_seed() #设置随机数种子,保证所有结果可以复现

        # 加载训练集、验证集、测试集
        print(f"{'加载训练集、验证集、测试集 Loading':*^80}")
        self.train_loader, self.valid_loader, self.test_loader = corpus.get_loaders()

        #加载model
        #self.model, self.tokenizer = self.load_model_tokenizer(model_name)


        self.model = model
        
        # move model to GPU
        if self.n_gpu > 1:
            device_ids = [0, 1, 2, 3]
            self.model =torch.nn.DataParallel(self.model, device_ids= device_ids)
        self.model = self.model.to(self.device)

        #loss function & optimizer
        # 带权重的损失函数, 若positive_label为1的f1_score为 0.75，positive_label为0的f1_score为0.85
        #self.loss_func = nn.CrossEntropyLoss(weight= torch.tensor([1.1765, 1.3333])).to(self.device)
        self.loss_func = nn.CrossEntropyLoss(weight=torch.tensor([0.5, 0.5])).to(self.device)
        self.optimizer = torch.optim.Adam(
                self.model.parameters(),
                lr = HYPERS["LR"],
                eps = 1e-8)




    """
    def load_model_tokenizer(self, model_name):
        #model_path = os.path.join(os.getcwd(), MODELS[model_name]["path"])
        model_path = MODELS[model_name]["path"]
        assert model_name in MODELS

        if self.retrain_model_path is None:

            print(f"### 从 {model_path} 加载预训练模型, 重新训练 ###")
            model = MODELS[model_name]["class"](model_path)
        else:
            print(f"{'加载已预训练好的模型,继续训练':*^80}")
            model = torch.load("./fintuned_model/" + self.retrain_model_path)

        print(f"## Model {self.model_name} loaded. ##")

        tokenizer = MODELS[model_name]["tokenizer"].from_pretrained(model_path)

        ## __class__.__name__输出类的名字
        print(f"## Tokenizer {tokenizer.__class__.__name__} loaded. ##")

        return model, tokenizer
    """
    
    def set_random_seed(self):
        # Set the seed value all over the place to make this reproducible.
        self.seed_val = 2021
        np.random.seed(self.seed_val)
        torch.manual_seed(self.seed_val)

    def set_device(self):
        ###设置日志时间的输出格式,说明在那段时间用过GPU
        LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
        DATE_FORMAT = "%m/%d/%Y %H:%M:%S %p"
        logging.basicConfig(filename='NLP_GPU.log', level=logging.DEBUG, format=LOG_FORMAT, datefmt=DATE_FORMAT)

        # 设置运行环境GPU
        self.device = torch.device("cuda:0")
        self.n_gpu = torch.cuda.device_count()
        logging.info(msg = f"\n Using GPU, {self.n_gpu} device available")

    def run_epoch(self):

        #list to store a number of quantities such as
        #training and validation loss, validation accuracy, and timings.
        training_stats = []


        #Total number of training steps is [number of batches × number of epochs]
        total_steps = len(self.train_loader) * HYPERS["EPOCHS"]
        # create the learning rate scheduler
        self.scheduler = get_linear_schedule_with_warmup(
            self.optimizer, num_warmup_steps = 100, num_training_steps = total_steps
        )

        total_t0 = time.time()

        print(f"### Trainng {HYPERS['EPOCHS']} EPOCHS start ###")
        for epoch in tqdm(range(1, HYPERS["EPOCHS"] + 1), unit = "epoch",
                          desc = f"Training All {HYPERS['EPOCHS']} Epochs"):
            # Measure how long the per training epoch takes
            t0 = time.time()

            # Put the model into training model
            print(f"### EPOCH {epoch} train  start")
            self.model.train()

            epoch_train_loss = self.train(epoch)
            # measure avg batch loss in specific epoch
            avg_train_loss = epoch_train_loss / len(self.train_loader)
            # Measure how long this epoch took.
            training_time = format_time(time.time() - t0)
            print(f"## per batch train loss for epoch {epoch} is {avg_train_loss} ",
                  f"total train time : {training_time}")

            t0 = time.time()

            # eval mode
            # 在eval模式下不会应用DROPOUT和BATCHNORM
            print(f"### EPOCH {epoch} val start")
            self.model.eval()

            epoch_eval_loss, eval_auc = self.eval(metric=roc_auc_score)
            avg_eval_loss = epoch_eval_loss / len(self.valid_loader)
            validation_time = format_time(time.time() - t0)
            print(f"## per batch valid loss for epoch {epoch} is {avg_eval_loss} ",
                  f"total valid time : {validation_time}, Validation auc score {eval_auc}")

            # Record all statistics from this epoch.
            training_stats.append(
                {
                    'Epoch': epoch,
                    'Train Loss': epoch_train_loss,
                    'Avg Train Loss': avg_train_loss,
                    'Train Time': training_time,
                    'Valid Loss': epoch_eval_loss,
                    'Avg Valid Loss': avg_eval_loss,
                    'Valid Time': validation_time,
                    'Valid AUC': eval_auc,
                    'Test Results Dir': 'Model{}_BATCH{}_LR{}/'.format(self.model_name,
                     HYPERS['BATCH_SIZE'], HYPERS['LR'])
                }
            )

        test_t0 = time.time()
        self.test()
        print("Test Time Consume {}".format(format_time(time.time() - test_t0)))
        self.save_stats(training_stats)
        print(f"{'Training complete !':*^80}")
        print(f"### Total Process took {format_time(time.time() - total_t0)} ####")


    def train(self, epoch):
        total_train_loss = 0

        for batch in tqdm(self.train_loader, desc=f"Epoch {epoch}>>>>train", unit="batch"):
            # input_ids, attention_mask, token_type_id和Label混在一起
            inputs = [data.to(self.device) for data in batch[:-1]]
            labels = batch[-1].to(self.device)
            outputs = self.model(*inputs)


            batch_loss = self.loss_func(outputs, labels)
            total_train_loss += batch_loss.to("cpu").data.numpy()
            # clear any previously calculated gradients before performing a backward pass.
            self.optimizer.zero_grad()

            # perform a backward pass to calculate the gradients
            batch_loss.backward()

            # normalization of the gradients to 1.0 to avoid exploding gradients
            nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)

            # update parameters and take a step using the computed gradient
            self.optimizer.step()

            #update the learning rate 
            self.scheduler.step()

            #print(f"per batch loss {batch_loss.to('cpu').data.numpy()}")

        return total_train_loss

    def eval(self, metric):
        total_eval_loss = 0
        predicted_scores = np.array([])
        target_labels = np.array([])
        #predicted_labels = np.array([])

        for batch in self.valid_loader:
            inputs = [data.to(self.device) for data in batch[:-1]]
            labels = batch[-1].to(self.device)

            # Tell pytorch not to bother with constructing the compute graph during
            # the forward pass, since this is only needed for backprop (training).
            with torch.no_grad():
                outputs = self.model(*inputs)
                loss = self.loss_func(outputs, labels)
                total_eval_loss += loss.to("cpu").data.numpy()

                # move logits and labels to CPU,存储在CPU上面的变量不能和存储在GPU上面的变量进行运算
                logits = F.softmax(outputs.to("cpu"), dim = 1).data.numpy()
                label_ids = labels.to("cpu").data.numpy()
                y_pred = logits[:, 1]
                #y_pred1 = np.argmax(logits, axis = 1)
                predicted_scores = np.append(predicted_scores, y_pred)
                #predicted_labels = np.append(predicted_labels, y_pred1)
                target_labels = np.append(target_labels, label_ids)


        task_auc = metric(target_labels, predicted_scores)

        #print(f"{'classification_report':*^80}")
        #print(classification_report(target_labels, predicted_labels))
        return total_eval_loss , task_auc

    def test(self):

        prediction_scores = np.array([])
        print(f"{'Predict task':*^80}")
        for batch in tqdm(self.test_loader, desc = "Predict Scores Loading", unit = "batch"):
            inputs = [data.to(self.device) for data in batch][0]

            with torch.no_grad():
                outputs = self.model(inputs)
                logits = F.softmax(outputs.to("cpu"), dim=1).data.numpy()
                y_pred = logits[:, 1]
                prediction_scores = np.append(prediction_scores, y_pred)

        self.save_predictions(prediction_scores)

    def save_predictions(self, predicts):
        file_path = "./finetuned_results/" + 'Model{}_BATCH{}_EPOCH{}_LR{}/'.format(self.model_name,
                  HYPERS['BATCH_SIZE'],HYPERS['EPOCHS'], HYPERS['LR'])
        if not os.path.exists(file_path):
            os.mkdir(file_path)

        #输出当前时间
        dt = str(datetime.datetime.now()).split(" ")[0]
        filename = "{}_{}_(对应id和score).json".format(self.model_name, dt)
        with open(file_path + filename, "w") as fw:
            for idx, predict in enumerate(predicts):
                predict = {"id": idx, "label": predict}
                json.dump(predict, fw)
                if idx == len(predicts) - 1:
                    break
                fw.write("\n")

        filename2 = "{}_{}_result.tsv".format(self.model_name, dt)
        with open(file_path + filename2, "w") as fw:
            for idx, predict in enumerate(predicts):
                fw.write(str(predict))
                if idx == len(predicts) - 1:
                    break
                fw.write("\n")

    def save_stats(self ,stats):
        df = pd.DataFrame(stats)
        filename = 'Stats_{}_BATCH{}_Epoch{}_LR{}.csv'.format(self.model_name, HYPERS['BATCH_SIZE'],
                            HYPERS['EPOCHS'], HYPERS['LR'])
        df.to_csv("./finetuned_results/" + filename, sep = ",", encoding="utf-8", index = False)

    def save_model(self):
        # 保存训练好的模型
        model_name = 'Model{}_BATCH{}_Epoch{}_LR{}_TIME{}.pkl'.format(self.model_name, HYPERS['BATCH_SIZE'],
        HYPERS['EPOCHS'], HYPERS['LR'],time.strftime("%Y_%m_%d_%H_%M",time.localtime()))
        torch.save(self.model, "./finetuned_model/" + model_name)
        print("Fintuned model saved")


if __name__ == "__main__":
    ## 使用编号为4,5的两张显卡
    #os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
    #os.environ["CUDA_VISIBLE_DEVICES"] = "4, 5, 6, 7"
    # global hyper parameters
    HYPERS = {
        "BATCH_SIZE":4,
        "LR": 5e-5,
        "EPOCHS": 7,
    }
    seed_val = 2021
    corpus = Corpus(HYPERS["BATCH_SIZE"], seed_val)
    class_num = 2
    maxlen = corpus.max_len
    max_features = len(corpus.vocab)
    embedding_dims = 400
    dropout_rate = 0.2
    feature_size = 1024
    kernel_sizes = [2, 3, 4, 5]

    print("Build model.....")
    model = TEXTCNN(maxlen=maxlen,
                    max_features=max_features,
                    embedding_dims=embedding_dims,
                    class_num=class_num,
                    kernel_sizes=kernel_sizes,
                    dropout_rate=dropout_rate,
                    feature_size=feature_size)
    app = fintune(model, corpus)
    app.run_epoch()
    #app.save_model()

********************************Data_precessing*********************************
## dataset size is 121105
*******************************Load  dataset ....*******************************
## Load Datasets Consume 0:00:06 s ###
************************All Train and Test Data loaded !************************
Build model.....
*****************************加载训练集、验证集、测试集 Loading******************************


Epoch 1>>>>train:   0%|                                                                   | 0/27249 [00:00<?, ?batch/s]

### Trainng 7 EPOCHS start ###
### EPOCH 1 train  start



Training All 7 Epochs:   0%|                                                                  | 0/7 [00:10<?, ?epoch/s]


KeyboardInterrupt: 

In [18]:
import pandas as pd
data = pd.read_csv("E:/lv_python/NLP/阿里天池小布助手/finetuned_results/2021-03-07_Linear_result.tsv", header = None, names = ["score"])
data1 = pd.read_csv(r"E:\lv_python\NLP\阿里天池小布助手\finetuned_results\TextCNN_2021-03-11_result.tsv", header = None, names = ["score"])

In [19]:
data

score
0      0.000220
1      0.969897
2      0.006519
3      0.056620
4      0.029994
...         ...
24995  0.000209
24996  0.000881
24997  0.996679
24998  0.003614
24999  0.959297

[25000 rows x 1 columns]

In [20]:
data1

score
0      0.268941
1      0.722515
2      0.268943
3      0.269112
4      0.276338
...         ...
24995  0.270007
24996  0.271409
24997  0.731059
24998  0.268964
24999  0.731054

[25000 rows x 1 columns]

In [26]:
for idx, (x, y) in enumerate(zip(data["score"], data1["score"])):
    print(idx, x, y)

0 0.00022005951905157417 0.2689414322376251
1 0.9698974490165709 0.7225145697593689
2 0.0065185949206352225 0.26894333958625793
3 0.05662039294838905 0.26911163330078125
4 0.029993537813425064 0.2763379514217377
5 0.9974032044410706 0.7310423851013184
6 0.00017127387400250882 0.2689414918422699
7 0.9992104768753052 0.731052041053772
8 0.7372874021530151 0.2755856812000275
9 0.9565937519073486 0.7209820747375488
10 0.9158976674079896 0.7179679274559021
11 9.49774621403776e-05 0.2689414620399475
12 0.9853309392929076 0.7310585975646973
13 6.0257705627009266e-05 0.2689415216445923
14 0.01780320517718792 0.2760138809680939
15 0.7582051753997803 0.2690070569515228
16 0.0023349737748503685 0.2689602673053741
17 0.0016782927559688687 0.2690020203590393
18 0.032146137207746506 0.27056971192359924
19 0.0019852144178003073 0.2701297700405121
20 0.4039240777492523 0.270845890045166
21 0.9985894560813904 0.7197993993759155
22 0.000705293205101043 0.2689414322376251
23 0.9991905093193054 0.73105859

763 0.07398803532123566 0.2689414322376251
764 0.008337900042533875 0.2689417004585266
765 0.9965448975563048 0.2689512073993683
766 0.11338501423597334 0.2692548036575317
767 0.003106718650087714 0.2689414322376251
768 0.9658424258232116 0.7308250069618225
769 0.9840934276580809 0.7310066819190979
770 0.08531506359577179 0.27135369181633
771 0.9952730536460876 0.7309961915016174
772 0.00021343711705412718 0.2689489722251892
773 0.9630703926086426 0.7310551404953003
774 0.00014220982848200947 0.2698700428009033
775 0.00012957953731529417 0.26894161105155945
776 0.9930949211120604 0.6717510819435121
777 0.9992353916168212 0.7310572862625122
778 0.004303284455090761 0.2689806818962097
779 0.9914680719375609 0.7300203442573547
780 0.0001837288436945528 0.2689645290374756
781 0.03561822697520256 0.2690106332302093
782 0.9874548912048341 0.7142139077186584
783 0.9998443126678468 0.7309423685073853
784 0.991567313671112 0.7306256890296936
785 0.07574532926082611 0.26916754245758057
786 0.993

1596 0.8104285597801208 0.5609470009803772
1597 7.391176040982829e-05 0.2691025733947754
1598 0.00023812337894923985 0.2689414322376251
1599 0.9978037476539612 0.7310564517974854
1600 0.996138870716095 0.7309667468070984
1601 0.014375693164765838 0.27243223786354065
1602 5.831550879520364e-05 0.2690715491771698
1603 0.9966975450515748 0.7204868793487549
1604 0.9860952496528624 0.27244627475738525
1605 0.9485780596733092 0.7284643650054932
1606 0.07043027877807617 0.27056294679641724
1607 0.0006488646613433957 0.2727612853050232
1608 0.9436883330345154 0.2689414322376251
1609 0.004615960642695427 0.2689426839351654
1610 0.973170042037964 0.7310161590576172
1611 0.0001378755841869861 0.2689414620399475
1612 0.989285171031952 0.7259142398834229
1613 0.009367463178932669 0.2689569890499115
1614 0.9807820320129396 0.7310574650764465
1615 0.9495787620544434 0.7310292720794678
1616 0.002622194122523069 0.2689414322376251
1617 0.19605199992656708 0.4977252185344696
1618 0.9938993453979492 0.73

2429 0.9967544674873352 0.7310584187507629
2430 0.5951200723648071 0.26896539330482483
2431 0.9918877482414246 0.7310238480567932
2432 0.01583172380924225 0.6136884689331055
2433 0.009356982074677944 0.2696368992328644
2434 0.9875475168228148 0.7302687168121338
2435 0.988788902759552 0.7305084466934204
2436 0.00012087672803318128 0.2689415216445923
2437 0.904111623764038 0.7309046387672424
2438 0.8034133911132812 0.7310529947280884
2439 0.0003213121672160924 0.2689414322376251
2440 0.9966468214988708 0.7310569286346436
2441 0.2557486593723297 0.4181042015552521
2442 0.004692669026553631 0.2689428627490997
2443 0.9980731010437012 0.7309066653251648
2444 0.06345824152231216 0.7308764457702637
2445 0.8817205429077148 0.6431431770324707
2446 0.9877380132675172 0.7310540676116943
2447 0.99686461687088 0.731053352355957
2448 0.963754415512085 0.4422342479228973
2449 0.9959557056427002 0.7310444712638855
2450 0.9924513697624208 0.7310193181037903
2451 0.3587362468242645 0.6698252558708191
245

3262 0.5171074271202087 0.388226717710495
3263 0.9994561076164246 0.7310582995414734
3264 0.9959914088249208 0.7127578854560852
3265 0.0036938393022865053 0.2689414322376251
3266 0.9951753616333008 0.7310585975646973
3267 7.645636651432142e-05 0.2689532935619354
3268 0.9967670440673828 0.7310360074043274
3269 0.00011342218931531534 0.2695719301700592
3270 0.3855124413967133 0.7301498055458069
3271 0.0003943385672755539 0.2689414322376251
3272 0.005746967624872923 0.2689414322376251
3273 0.0007943408563733102 0.26902976632118225
3274 0.005489120725542307 0.2720305621623993
3275 0.999543070793152 0.7310583591461182
3276 0.009399895556271076 0.2689415514469147
3277 0.9629215002059937 0.7309508323669434
3278 0.00039132824167609215 0.2689414322376251
3279 0.9992367029190063 0.731056809425354
3280 0.9826205372810364 0.7310584783554077
3281 0.00029260604060254986 0.2692214846611023
3282 0.9025434255599976 0.7310580611228943
3283 0.0009397048270329832 0.26894211769104004
3284 0.001318082213401

4095 0.9996110796928406 0.7310583591461182
4096 0.9966688752174376 0.7310581207275391
4097 0.8631929159164429 0.7309474349021912
4098 0.022819044068455696 0.2690529525279999
4099 0.006943380460143089 0.26915380358695984
4100 0.0005438522784970701 0.26943203806877136
4101 0.7089390754699707 0.3213880658149719
4102 0.004812170285731554 0.268941730260849
4103 0.00014005399134475738 0.2689414322376251
4104 0.9730409979820251 0.7310067415237427
4105 0.002307390794157982 0.2690007984638214
4106 0.0015911079244688153 0.2689415514469147
4107 0.0003740849206224084 0.2690199017524719
4108 0.9664921760559082 0.7310585975646973
4109 0.0026534618809819217 0.2690280973911285
4110 0.1642249971628189 0.3309018015861511
4111 0.32088401913642883 0.2689414620399475
4112 0.0001292685337830335 0.2689414322376251
4113 0.002023611683398485 0.2691871523857117
4114 5.550495916395448e-05 0.2689434885978699
4115 0.992404282093048 0.7310400009155273
4116 8.506082667736337e-05 0.2718791663646698
4117 0.96424371004

4929 0.9956943988800048 0.7310194969177246
4930 0.0002714347210712731 0.269180029630661
4931 0.00040846833144314587 0.2689414322376251
4932 0.8294083476066589 0.7310580611228943
4933 0.9923094511032104 0.5823253393173218
4934 0.3625554144382477 0.27005350589752203
4935 0.9962685108184814 0.730935275554657
4936 0.0004091639711987227 0.26894161105155945
4937 0.9981694221496582 0.7310500741004944
4938 0.00022393224935512987 0.2696950435638428
4939 0.994101583957672 0.7310397624969482
4940 0.0036841020919382572 0.2690711617469788
4941 0.9635160565376282 0.7310231328010559
4942 0.9992349147796632 0.7310585975646973
4943 0.9981223940849304 0.7305154204368591
4944 0.9995961785316468 0.7310546040534973
4945 0.998770534992218 0.7310585975646973
4946 0.9895573258399964 0.7276027798652649
4947 0.9971346855163574 0.731056809425354
4948 0.10382433235645294 0.26981210708618164
4949 0.994586706161499 0.7310568690299988
4950 0.9632526636123656 0.7310583591461182
4951 0.9995532631874084 0.7310377359390

5721 0.9948699474334716 0.7310585975646973
5722 0.0767926350235939 0.2691493332386017
5723 0.001451610354706645 0.2689424157142639
5724 0.9975464940071106 0.3878359496593475
5725 0.2521997392177582 0.30015960335731506
5726 0.12038733065128325 0.270880788564682
5727 0.009894381277263165 0.3450279533863068
5728 0.979925274848938 0.731054425239563
5729 0.06170796975493431 0.2724181115627289
5730 0.0012121853651478887 0.26895725727081304
5731 0.02710555680096149 0.349008709192276
5732 0.3104245364665985 0.2690602242946625
5733 0.00052625936223194 0.2689430117607117
5734 0.039572440087795265 0.3014397025108337
5735 0.00010504732927074656 0.2689414322376251
5736 0.010536331683397291 0.26914623379707336
5737 0.4638054072856903 0.7310394644737244
5738 0.001716720056720078 0.2689637243747711
5739 0.985891044139862 0.7310463786125183
5740 0.001012293854728341 0.2689415216445923
5741 0.5991647839546204 0.7310527563095093
5742 0.982148051261902 0.7309670448303223
5743 0.9837661981582642 0.73105794

6532 0.00019972589507233351 0.2689414322376251
6533 0.00027816672809422016 0.2689414322376251
6534 0.9971349239349364 0.7310585975646973
6535 0.9994899034500122 0.7310566902160645
6536 0.00023088724992703646 0.2689414322376251
6537 0.9993777275085448 0.7310582399368286
6538 0.03729826211929321 0.2690024971961975
6539 0.0047183423303067675 0.2743140459060669
6540 0.5786733031272888 0.7292852401733398
6541 0.01475792657583952 0.2776336073875427
6542 0.022623177617788315 0.27323299646377563
6543 0.008093045093119144 0.2689845263957977
6544 5.5590353440493345e-05 0.2689414322376251
6545 0.9991946816444396 0.2760171592235565
6546 0.999397873878479 0.7310578227043152
6547 0.00021231612481642517 0.26894333958625793
6548 0.17164885997772214 0.7310365438461304
6549 0.0017487419536337256 0.2689710855484009
6550 0.8466094732284546 0.7310491800308228
6551 0.001907449797727168 0.2771338224411011
6552 0.01080786157399416 0.2882493734359741
6553 0.02238182909786701 0.26897332072258
6554 0.00020552988

7261 0.966330885887146 0.7310554981231691
7262 0.00017485700664110482 0.2689414322376251
7263 0.0018023393349722028 0.2689414322376251
7264 0.9750466346740724 0.7310585379600525
7265 0.00013361289165914061 0.2689414322376251
7266 0.0027520572766661644 0.26899755001068115
7267 0.9985299110412598 0.7299175858497621
7268 0.9996562004089355 0.731057345867157
7269 0.002188111189752817 0.2735195159912109
7270 0.0003960930916946381 0.2689470946788788
7271 0.000672014313749969 0.26926153898239136
7272 0.8693332672119141 0.7310565710067749
7273 0.7612802386283875 0.30017805099487305
7274 0.6920632719993591 0.7310569882392883
7275 0.9974160194396972 0.7310009598731995
7276 0.04154191911220551 0.2723031044006348
7277 0.0014289994724094868 0.2720966637134552
7278 0.0049879983998835095 0.2689414322376251
7279 0.08584774285554886 0.2696326971054077
7280 0.7880392670631409 0.2689887583255768
7281 0.00020817744371015576 0.268959105014801
7282 0.4252234995365143 0.6668639183044434
7283 0.01790568605065

8095 0.030938638374209407 0.2799624502658844
8096 0.015889478847384453 0.26894161105155945
8097 0.6477501392364502 0.2689777612686157
8098 0.007549266330897808 0.2692785859107971
8099 0.00012536153371911496 0.2689414322376251
8100 0.9990425705909728 0.7310560345649719
8101 0.0036167041398584843 0.7074474692344666
8102 0.9846068620681764 0.7310509085655212
8103 0.9996498823165894 0.7310502529144287
8104 0.999792754650116 0.7310585975646973
8105 0.9973574280738832 0.7306498289108276
8106 0.008000500500202179 0.2690029740333557
8107 0.9577975273132324 0.7310492992401123
8108 0.015902524814009666 0.2719849646091461
8109 0.08925087004899979 0.2689490020275116
8110 0.996806263923645 0.7310582995414734
8111 0.9992195367813109 0.7310572266578674
8112 0.0012753815390169618 0.2692306339740753
8113 0.0009358556126244367 0.2689414322376251
8114 0.944757640361786 0.7310584187507629
8115 0.9914914965629578 0.7310582399368286
8116 0.0003367007593624294 0.2689414322376251
8117 0.9758177995681764 0.731

8928 6.495020352303982e-05 0.2689414322376251
8929 0.00027117712306790054 0.2689456045627594
8930 0.016716329380869862 0.3495757579803467
8931 0.9898514747619628 0.7310585975646973
8932 0.9933710098266602 0.7310070395469666
8933 0.0001187227389891632 0.2689495086669922
8934 0.0021045843604952093 0.7310584187507629
8935 0.014515825547277927 0.269004762172699
8936 0.9909040331840516 0.7310380935668945
8937 0.9988619089126588 0.7310073971748352
8938 0.99429589509964 0.2760244905948639
8939 0.972672164440155 0.7310583591461182
8940 0.3351315259933472 0.2740822434425354
8941 0.1953001618385315 0.269540935754776
8942 0.9947777986526488 0.7298554182052612
8943 0.999304175376892 0.7310507893562317
8944 0.977367103099823 0.7310263514518738
8945 0.9768345952033995 0.7309975624084473
8946 0.989953875541687 0.7310565710067749
8947 0.9623221158981324 0.7310577630996704
8948 0.009900606237351894 0.2689444124698639
8949 0.12364903092384337 0.2689851522445679
8950 7.503417873522267e-05 0.2689414322376

9795 0.94463711977005 0.7310066223144531
9796 0.943452000617981 0.63225257396698
9797 0.9892423748970032 0.7310585975646973
9798 0.9806416630744934 0.7308369874954224
9799 0.9981162548065186 0.7310096025466919
9800 0.9988754391670228 0.7309641242027283
9801 0.9986292123794556 0.7310433387756348
9802 0.0008233605767600237 0.2689767777919769
9803 0.03872000053524971 0.2696802616119385
9804 0.9307220578193665 0.27015960216522217
9805 0.9637691378593444 0.7310327887535095
9806 0.2919091582298279 0.2689456641674042
9807 0.9905421137809752 0.7310568690299988
9808 0.9665971994400024 0.7310582399368286
9809 6.938110163901001e-05 0.26894810795784
9810 0.002988141495734453 0.2787761390209198
9811 0.9932398796081544 0.7310585379600525
9812 0.9960073828697203 0.7310585975646973
9813 0.9819122552871704 0.7310438752174377
9814 0.0013971166918054225 0.2689414322376251
9815 3.0337398129631762e-05 0.2689741551876068
9816 0.5998578667640686 0.5415014028549194
9817 0.9300329685211182 0.73105788230896
981

10594 0.9838995933532716 0.7309762835502625
10595 0.8351732492446899 0.7299668192863464
10596 0.4956998229026794 0.2689414322376251
10597 0.9992432594299316 0.7308971881866455
10598 0.9606990814208984 0.7310575842857361
10599 0.19293902814388275 0.731054425239563
10600 0.0008948628674261273 0.2689618766307831
10601 0.9918137788772584 0.7310584783554077
10602 0.005074420012533665 0.2689420580863953
10603 0.998396933078766 0.7310420870780945
10604 0.9883528351783752 0.3642091751098633
10605 0.9775132536888124 0.7310363054275513
10606 0.9788194298744202 0.6797345876693726
10607 0.9990087151527404 0.7309436798095703
10608 0.005662646144628525 0.2689414322376251
10609 0.9976467490196228 0.7310468554496765
10610 0.15017999708652496 0.35348862409591675
10611 0.6000382304191589 0.2695399820804596
10612 0.9996669292449952 0.731039822101593
10613 0.9810395240783693 0.7309859991073608
10614 0.991341769695282 0.7310583591461182
10615 0.09622228145599364 0.2689509093761444
10616 0.00898559857159853

11514 0.9491992592811584 0.73104327917099
11515 0.985631227493286 0.7309714555740356
11516 0.01852094940841198 0.2689432501792908
11517 0.016465749591588974 0.2692418098449707
11518 0.9983506202697754 0.731039822101593
11519 0.36490398645401 0.6259316205978394
11520 0.016433047130703926 0.2689761221408844
11521 0.9992891550064088 0.73105788230896
11522 0.9973251819610596 0.7310569286346436
11523 0.31400448083877563 0.2689414322376251
11524 0.8285336494445801 0.26902350783348083
11525 0.00021998022566549483 0.2689490914344788
11526 0.00023214037355501205 0.2690065801143646
11527 0.8896594643592834 0.7310553193092346
11528 0.00021597289014607668 0.26894164085388184
11529 0.0001243214646819979 0.2692964673042297
11530 0.8401164412498474 0.7103011012077332
11531 0.0014620438450947404 0.2715277373790741
11532 0.008851269260048866 0.2689414322376251
11533 0.9988582134246826 0.7310522198677063
11534 0.048766132444143295 0.27259594202041626
11535 0.0004894023295491934 0.2689414322376251
11536 

12401 0.9915505647659302 0.7307916283607483
12402 0.5985941886901855 0.7304835319519043
12403 0.9934372305870056 0.7310509681701659
12404 0.9924496412277222 0.7301753759384155
12405 0.945261001586914 0.7310431599617004
12406 0.0053336042910814285 0.26897168159484863
12407 0.06892308592796326 0.2697880864143372
12408 0.9988563060760498 0.7310585975646973
12409 0.003468016628175974 0.2689540684223175
12410 0.005891448352485895 0.7308720350265503
12411 0.00016840880562085658 0.2689609229564667
12412 0.010056919418275356 0.2689437866210937
12413 0.9989742040634156 0.7310582399368286
12414 0.02294013649225235 0.7309166789054871
12415 0.9897547364234924 0.7310572862625122
12416 0.012882846407592295 0.41730380058288574
12417 0.0001950272562680766 0.2689414322376251
12418 0.008056121878325941 0.2689811885356903
12419 0.00014054012717679143 0.2689414322376251
12420 0.001015792950056493 0.2689920663833618
12421 0.007011387497186661 0.2689525187015533
12422 0.492508739233017 0.2753790318965912
12

13186 0.997012972831726 0.7310569286346436
13187 0.9995744824409484 0.7310585975646973
13188 0.0001949383731698617 0.26894351840019226
13189 0.9944807291030884 0.3105016052722931
13190 0.8859820365905762 0.7310429215431213
13191 0.9991784691810608 0.7310575842857361
13192 0.9891874194145204 0.7310577034950256
13193 0.0037221508100628853 0.720917820930481
13194 0.9987078905105592 0.7310585975646973
13195 0.2228192389011383 0.2691514492034912
13196 0.00011478332453407349 0.2689414322376251
13197 0.0010045139351859687 0.2689414322376251
13198 0.9712105989456176 0.5875354409217834
13199 0.04215242713689804 0.2734687328338623
13200 0.0002089587796945125 0.2689539194107056
13201 0.00016383934416808188 0.2689414918422699
13202 0.05904854089021683 0.26911306381225586
13203 0.9960182309150696 0.7310547828674316
13204 0.5854071378707886 0.7310584783554077
13205 0.9973160624504088 0.7310572266578674
13206 0.9993711113929749 0.729351282119751
13207 0.9900013208389282 0.7310577630996704
13208 0.801

14093 0.06634631007909775 0.2689523994922638
14094 0.0004890448763035238 0.2689414322376251
14095 0.005537926685065031 0.2707589864730835
14096 0.00027157244039699435 0.2690615952014923
14097 0.00873960368335247 0.3736685514450073
14098 0.999151349067688 0.7310583591461182
14099 0.4568404257297516 0.26931920647621155
14100 0.9996557235717772 0.7310584783554077
14101 0.9895544052124025 0.7287667393684387
14102 0.004255023319274187 0.2693404853343964
14103 0.0007454952574335039 0.26894161105155945
14104 0.4581919014453888 0.44517165422439575
14105 0.9730336666107178 0.7310407161712646
14106 0.05009859800338745 0.2690827250480652
14107 0.9764831066131592 0.7310023307800293
14108 0.9828400015830994 0.7310506701469421
14109 0.9335986375808716 0.2942957878112793
14110 0.6268520355224609 0.7304608225822449
14111 0.002648708876222372 0.26957443356513977
14112 0.9367284178733826 0.7310482263565063
14113 0.01944948174059391 0.2689415514469147
14114 0.9993962049484252 0.7310569286346436
14115 0.1

14940 0.6297722458839417 0.29073286056518555
14941 0.0009178813197650015 0.7307464480400085
14942 0.00010244746226817371 0.2689414322376251
14943 0.0013059735065326095 0.268945187330246
14944 0.9968499541282654 0.7310585379600525
14945 0.0004942264058627188 0.2689661681652069
14946 0.00016791015514172614 0.2689415216445923
14947 0.0008769349660724401 0.2690246403217316
14948 0.00012140971375629307 0.2689429223537445
14949 0.00015929648361634463 0.2689414322376251
14950 0.9098260402679444 0.7309717535972595
14951 0.008443055674433708 0.2690984010696411
14952 0.006053038872778416 0.2691182792186737
14953 0.8983141779899597 0.7310249805450441
14954 0.9983282685279846 0.7310516238212585
14955 0.8011755347251892 0.7309467196464539
14956 0.908578872680664 0.7310583591461182
14957 0.00037901580799371004 0.26895424723625183
14958 0.003122392576187849 0.2689618766307831
14959 0.0012211098801344633 0.2689518928527832
14960 0.01676265150308609 0.26927730441093445
14961 0.0015998885501176119 0.271

15760 0.9989582300186156 0.7310067415237427
15761 0.0009702583774924277 0.2689414322376251
15762 0.9902661442756652 0.7187420129776001
15763 0.007981113158166409 0.2689436376094818
15764 0.9995513558387756 0.7310585975646973
15765 0.0008372291922569275 0.28051209449768066
15766 0.9974263310432434 0.7310579419136047
15767 0.993093490600586 0.7310450077056885
15768 0.9992511868476868 0.7310084104537964
15769 0.4482473134994507 0.6720581650733948
15770 0.010224808007478714 0.26894333958625793
15771 0.9896668195724488 0.7310577034950256
15772 0.8884126543998718 0.2700883746147156
15773 0.8518125414848328 0.7252472043037415
15774 0.0027052471414208412 0.2689558565616608
15775 0.024734679609537125 0.2696059346199036
15776 0.9997923970222472 0.7310557961463928
15777 0.0001502745144534856 0.26894721388816833
15778 0.9988290667533876 0.7310022711753845
15779 0.00032568007009103894 0.3507998287677765
15780 0.9866822957992554 0.7310440540313721
15781 0.06927047669887543 0.2695574760437012
15782 0

16593 0.002315470715984702 0.2710733711719513
16594 0.28120556473731995 0.7229833602905273
16595 0.00029926747083663935 0.2689414322376251
16596 0.06776855140924454 0.2689426839351654
16597 0.9998639822006226 0.7310540080070496
16598 0.999135673046112 0.7310585975646973
16599 0.00018009341147262606 0.2689414322376251
16600 0.0030912889633327727 0.2689414322376251
16601 0.9704593420028688 0.7310564517974854
16602 0.18769969046115875 0.6958102583885193
16603 0.015758277848362926 0.26941901445388794
16604 0.9837226271629332 0.7309924960136414
16605 0.949753999710083 0.7310492992401123
16606 0.9929335117340088 0.7310365438461304
16607 0.99614018201828 0.7310156822204591
16608 0.9204552173614502 0.7310467958450317
16609 0.9558559656143188 0.7310226559638977
16610 0.001144678913988173 0.27140799164772034
16611 0.007813234813511372 0.2689415216445923
16612 0.029542418196797367 0.2689414322376251
16613 0.00014076061779633164 0.2689414918422699
16614 0.9981215596199036 0.7310585379600525
16615 

17375 0.0005786979454569519 0.2689414322376251
17376 0.0015907299239188433 0.2689414322376251
17377 0.9891575574874878 0.7310585975646973
17378 0.022691726684570312 0.26906758546829224
17379 0.0003942286421079189 0.26897022128105164
17380 0.01051255688071251 0.2689618170261383
17381 0.9978785514831544 0.3688700199127197
17382 0.00830416288226843 0.2689436972141266
17383 0.9985985159873962 0.7310546040534973
17384 0.9977158308029176 0.7294226884841919
17385 0.8668493032455444 0.7305545806884766
17386 0.9970014691352844 0.7310553789138794
17387 0.0009617813047952949 0.27118635177612305
17388 0.7411845326423645 0.2690317928791046
17389 0.9809072613716124 0.7305571436882019
17390 0.18054740130901334 0.270977795124054
17391 0.9745474457740784 0.7310574650764465
17392 0.0004470408603083343 0.27173617482185364
17393 0.6613134741783142 0.7300444841384888
17394 0.00046124981599859893 0.2689414322376251
17395 0.9910752773284912 0.7130420804023743
17396 0.991751492023468 0.7310130596160889
17397 

18129 0.0012241931399330495 0.26917141675949097
18130 0.9992374181747437 0.7310583591461182
18131 0.00048600471927784383 0.2690231502056122
18132 0.00014693578123115006 0.26899927854537964
18133 0.020889334380626682 0.2689491808414459
18134 0.9685298204421996 0.7310270071029663
18135 0.00013711386418435725 0.2689414322376251
18136 0.9790350198745728 0.730651319026947
18137 0.00020942732226103544 0.2689414322376251
18138 0.9921243786811828 0.7306739091873169
18139 0.9581019282341005 0.7308964133262634
18140 0.995335042476654 0.7310527563095093
18141 0.6222956776618958 0.7310564517974854
18142 0.038956962525844574 0.2698062360286713
18143 0.010477733798325062 0.7060791254043579
18144 0.997380554676056 0.7306814789772034
18145 0.93507581949234 0.2689976096153259
18146 0.05648249015212059 0.3007057905197144
18147 0.9988746047019958 0.7310583591461182
18148 0.14603544771671295 0.34944358468055725
18149 0.902945637702942 0.6707083582878113
18150 0.007430457975715399 0.2728002071380615
18151 

18951 0.9845529794692992 0.7310377359390259
18952 0.003392523154616356 0.2689414322376251
18953 0.0003838155826088041 0.2689414322376251
18954 0.9997162222862244 0.7310584783554077
18955 0.9979966282844543 0.7298892140388489
18956 0.9975225329399108 0.7310570478439331
18957 0.9951366782188416 0.2765830755233765
18958 0.022211385890841484 0.2689496278762817
18959 0.0007668875041417778 0.26923757791519165
18960 0.015930069610476494 0.2699355185031891
18961 0.9063832759857178 0.7310369610786438
18962 0.0010063617955893278 0.2689724862575531
18963 0.016921581700444218 0.2689422070980072
18964 0.055745698511600494 0.6213213205337524
18965 0.9848920106887816 0.7307684421539307
18966 0.9863914251327516 0.7310585379600525
18967 0.9902082681655884 0.7310572266578674
18968 0.9950454235076904 0.7308744788169861
18969 0.5107662677764893 0.26899102330207825
18970 0.9837669134140016 0.7310584783554077
18971 0.9795237183570862 0.7308829426765442
18972 0.9871066212654114 0.7308885455131531
18973 0.000

KeyboardInterrupt: 

In [28]:
file_path = "E:/lv_python/NLP/阿里天池小布助手/finetuned_results/"
filename2 = "new_result.tsv"
with open(file_path + filename2, "w") as fw:
        for idx, (score, score1)  in enumerate(zip(data["score"], data["score"])):
            new_score = (score + score1)/ 2
            fw.write(str(new_score))
            if idx == len(data) - 1:
                break
            fw.write("\n")

In [5]:
import os
os.listdir("E:/lv_python/NLP/阿里天池小布助手/finetuned_results/")

['2021-03-07_Linear_result.tsv',
 '2021-03-07_Linear_result.zip',
 '2021-03-07_result&oldtrain.zip',
 '2021-03-07_result.zip',
 'ChineseRobertaAttention_2021-03-02_result.zip',
 'ChineseRobertaAttention_2021-03-03_result.zip',
 'ChineseRobertaAttention_2021-03-06_result.zip',
 'ChineseRobertaLinear_2021-03-02_result.zip',
 'TextCNN_2021-03-11_result.tsv',
 'TextCNN_2021-03-11_result.zip']

In [6]:
os.path.exists("E:/lv_python/NLP/阿里天池小布助手/finetuned_results/2021-03-07_Linear_result.csv")

False

In [123]:
import tensorflow as tf
import pandas as pd
from tensorflow import keras
from gensim.models import Word2Vec
import numpy as np

train_data = pd.read_csv("../tianchi_datasets/track3_round1_newtrain3.tsv", sep="\t", header=None,
                                 names=["sentence1", "sentence2", "labels"])
train_data["document"] = train_data["sentence1"].str.cat(train_data["sentence2"], sep = " [SEP] ")
test_data = pd.read_csv("../tianchi_datasets/track3_round1_testA.tsv", sep="\t", header=None,
                                names=["sentence1", "sentence2"])
test_data["document"] = test_data["sentence1"].str.cat(test_data["sentence2"], sep=" [SEP] ")

tokenizer = keras.preprocessing.text.Tokenizer(num_words = 7000, lower=False, filters = "", split = " ")
tokenizer.fit_on_texts(list(train_data["document"].values) + list(test_data["document"].values))
word_vocab = tokenizer.word_index

all_data = pd.concat([train_data["document"], test_data["document"]])
file_name = "./Word2vec_200.model"
model = Word2Vec([[word for word in document.split(" ")] for document in all_data.values],
                size = 400, window = 5, iter = 1, workers=12, seed = 2021, min_count = 2, sg = 1)
model.save(file_name)
model.wv.save_word2vec_format("./Word2Vec_200.bin", binary= True)

embedding_matrix = np.zeros((len(word_vocab), 400))
for word, i in word_vocab.items():
    embedding_vector = model.wv[word] if word in model else None
    if embedding_matrix is None:
        embedding_matrix[i-1] = embedding_vector
    else:
        unk_vec = np.random.random(400) * 0.5
        unk_vec = unk_vec - unk_vec.mean()
        embedding_matrix[i-1] = unk_vec
        
Word2Vec_model = gensim.models.KeyedVectors.load_word2vec_format('./Word2Vec_200.bin',binary=True)

d:\anaconda\envs\gluon1\lib\site-packages\ipykernel_launcher.py:27: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).


In [57]:
from tensorflow import keras

In [58]:
from gensim.models import Word2Vec

In [59]:
tokenizer = keras.preprocessing.text.Tokenizer(num_words = 7000, lower=False, filters = "", split = " ")

In [62]:
tokenizer.fit_on_texts(list(train_data["document"].values) + list(test_data["document"].values))

In [63]:
train_ = tokenizer.texts_to_sequences(train_data["document"].values)

In [64]:
test_ = tokenizer.texts_to_sequences(test_data["document"].values)


In [65]:
train_ = keras.preprocessing.sequence.pad_sequences(train_, maxlen = 120, padding = "post")
test_ = keras.preprocessing.sequence.pad_sequences(test_, maxlen = 120, padding = "post")

In [66]:
word_vocab = tokenizer.word_index

In [69]:
all_data = pd.concat([train_data["document"], test_data["document"]])
file_name = "./Word2vec_200.model"
model = Word2Vec([[word for word in document.split(" ")] for document in all_data.values],
                size = 400, window = 5, iter = 1, workers=12, seed = 2021, min_count = 2, sg = 1)

In [ ]:
model.save()

In [76]:
import numpy as np

In [84]:
embedding_matrix = np.zeros((len(word_vocab), 400))
for word, i in word_vocab.items():
    embedding_vector = model.wv[word] if word in model else None
    if embedding_matrix is None:
        embedding_matrix[i-1] = embedding_vector
    else:
        unk_vec = np.random.random(400) * 0.5
        unk_vec = unk_vec - unk_vec.mean()
        embedding_matrix[i-1] = unk_vec


d:\anaconda\envs\gluon1\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [86]:
len(embedding_matrix)

20601

In [87]:
import torch.nn as nn

In [95]:
import torch

In [96]:
emb = nn.Embedding.from_pretrained(torch.from_numpy(embedding_matrix))

In [99]:
import gensim

In [116]:
model.wv.save_word2vec_format("./Word2Vec_200.bin", binary= True)

In [118]:
Glove_model = gensim.models.KeyedVectors.load_word2vec_format('./Word2Vec_200.bin',binary=True)

In [130]:
import os
os.path.join("aa", "11")

'aa\\11'

In [146]:
emb(torch.LongTensor([[1]]))

tensor([[[ 8.6578e-02,  3.0881e-02,  5.4454e-02, -7.3786e-02, -2.2100e-01,
          -1.8517e-01, -9.1496e-02, -4.8742e-02,  6.2208e-02,  1.9237e-01,
          -2.3942e-01, -1.9800e-01, -2.1278e-01, -1.2114e-01, -1.4666e-01,
          -2.4913e-01,  3.7598e-02,  1.5293e-01, -1.1670e-03,  1.2145e-01,
          -1.8280e-02, -3.7732e-02, -9.9101e-02, -1.0589e-01,  1.8027e-01,
           2.2108e-01,  2.3163e-01,  2.3165e-01, -1.8647e-01,  8.5880e-02,
          -3.3081e-05, -1.1212e-01,  7.7813e-03,  2.1350e-01,  2.2863e-01,
          -2.0667e-02,  1.5393e-01, -3.8942e-02,  2.3829e-01,  1.8068e-01,
          -1.6188e-02, -6.8675e-03,  9.3522e-02,  5.4541e-02,  1.3982e-01,
           2.2968e-01,  7.4804e-02,  1.4016e-01,  7.9399e-02, -1.6915e-01,
           2.2485e-01,  1.0217e-01, -8.6826e-02,  8.4854e-02,  1.2325e-01,
          -2.2097e-01, -1.6086e-01,  8.9137e-02, -1.0869e-01, -2.1970e-01,
          -2.2921e-01, -1.6565e-01, -7.2503e-02,  8.4164e-03,  1.2088e-01,
           1.2985e-01,  9

In [145]:
embedding_matrix[0]

array([ 0.21711851, -0.11453386,  0.20077436, -0.05951488, -0.01232518,
        0.03963866,  0.24062929,  0.03123681, -0.04824853,  0.17596446,
        0.23107955,  0.09757179, -0.11815269, -0.07931834,  0.03433276,
        0.07799488, -0.04514416, -0.04940597,  0.19927388,  0.00592177,
       -0.16083231,  0.0315973 ,  0.00370703,  0.04645856, -0.07964959,
       -0.22261941,  0.18239956,  0.19892876, -0.02461764, -0.13521182,
       -0.02068985,  0.08519185, -0.2274013 , -0.11952821,  0.243154  ,
        0.20452446,  0.1480278 , -0.17845782,  0.13793747,  0.13007339,
       -0.24536355,  0.22856525, -0.02006326, -0.16872926, -0.17575469,
        0.11197394,  0.19310794, -0.11045123,  0.08552285,  0.00681663,
        0.24139888,  0.04866541, -0.07261371,  0.1455036 ,  0.15419056,
        0.00046861,  0.06077297, -0.01067   ,  0.15642028,  0.23849347,
       -0.2077974 , -0.07605521,  0.20200524, -0.21107796, -0.24078328,
        0.05012004, -0.04569194, -0.03846197,  0.24694546,  0.14

In [143]:
emb(torch.LongTensor([[1]]))

torch.Size([1, 1, 400])

In [133]:
len(word_vocab)

20601

In [131]:
word_vocab

{'[SEP]': 1,
 '12': 2,
 '29': 3,
 '19': 4,
 '23': 5,
 '16': 6,
 '11': 7,
 '10': 8,
 '9': 9,
 '32': 10,
 '39': 11,
 '161': 12,
 '126': 13,
 '48': 14,
 '243': 15,
 '43': 16,
 '106': 17,
 '5': 18,
 '6': 19,
 '72': 20,
 '66': 21,
 '8': 22,
 '13': 23,
 '283': 24,
 '282': 25,
 '459': 26,
 '28': 27,
 '370': 28,
 '317': 29,
 '62': 30,
 '76': 31,
 '247': 32,
 '140': 33,
 '276': 34,
 '50': 35,
 '46': 36,
 '169': 37,
 '80': 38,
 '300': 39,
 '47': 40,
 '202': 41,
 '59': 42,
 '217': 43,
 '431': 44,
 '45': 45,
 '127': 46,
 '134': 47,
 '426': 48,
 '536': 49,
 '67': 50,
 '447': 51,
 '230': 52,
 '24': 53,
 '133': 54,
 '522': 55,
 '52': 56,
 '533': 57,
 '432': 58,
 '227': 59,
 '251': 60,
 '226': 61,
 '253': 62,
 '453': 63,
 '168': 64,
 '358': 65,
 '629': 66,
 '25': 67,
 '272': 68,
 '176': 69,
 '267': 70,
 '102': 71,
 '55': 72,
 '462': 73,
 '153': 74,
 '79': 75,
 '421': 76,
 '173': 77,
 '130': 78,
 '334': 79,
 '347': 80,
 '101': 81,
 '524': 82,
 '525': 83,
 '335': 84,
 '44': 85,
 '360': 86,
 '200': 87,
 

In [148]:
emb1 = nn.Embedding.from_pretrained(torch.FloatTensor([[1, 2, 3], [4, 5, 6]]))

In [152]:
emb1(torch.LongTensor([[0]]))

tensor([[[1., 2., 3.]]])

In [155]:
emb = nn.Embedding.from_pretrained(torch.from_numpy(embedding_matrix))

In [157]:
emb(torch.LongTensor([[0]]))

tensor([[[ 0.2171, -0.1145,  0.2008, -0.0595, -0.0123,  0.0396,  0.2406,
           0.0312, -0.0482,  0.1760,  0.2311,  0.0976, -0.1182, -0.0793,
           0.0343,  0.0780, -0.0451, -0.0494,  0.1993,  0.0059, -0.1608,
           0.0316,  0.0037,  0.0465, -0.0796, -0.2226,  0.1824,  0.1989,
          -0.0246, -0.1352, -0.0207,  0.0852, -0.2274, -0.1195,  0.2432,
           0.2045,  0.1480, -0.1785,  0.1379,  0.1301, -0.2454,  0.2286,
          -0.0201, -0.1687, -0.1758,  0.1120,  0.1931, -0.1105,  0.0855,
           0.0068,  0.2414,  0.0487, -0.0726,  0.1455,  0.1542,  0.0005,
           0.0608, -0.0107,  0.1564,  0.2385, -0.2078, -0.0761,  0.2020,
          -0.2111, -0.2408,  0.0501, -0.0457, -0.0385,  0.2469,  0.1462,
          -0.1372, -0.0140, -0.1053, -0.1936,  0.0068, -0.2152, -0.0693,
           0.0827, -0.0820, -0.2165, -0.0807,  0.1375, -0.1709, -0.0499,
           0.1620,  0.1435,  0.1577,  0.2256,  0.0677, -0.2259, -0.0060,
           0.0784,  0.1071, -0.2328, -0.0948, -0.04

In [1]:
import time
import datetime

def format_time(elapsed):
    elapsed_rounded = int(round(elapsed))
    return str(datetime.timedelta(seconds = elapsed_rounded))

In [2]:
format_time(1000)

'0:16:40'

In [69]:
from Data_generator_vocab import Corpus

HYPERS = {
        "BATCH_SIZE":4,
        "LR": 5e-5,
        "EPOCHS": 7,
    }
seed_val = 2021
corpus = Corpus(HYPERS["BATCH_SIZE"], seed_val)
class_num = 2
maxlen = corpus.max_len
max_features = len(corpus.vocab)
embedding_dims = 400
dropout_rate = 0.2
feature_size = 1024
kernel_sizes = [2, 3, 4, 5]


********************************Data_precessing*********************************
## dataset size is 121105
*******************************Load  dataset ....*******************************
## Load Datasets Consume 0:00:10 s ###
************************All Train and Test Data loaded !************************


In [70]:
len(corpus.v2i)

20601

In [71]:
max_features

20601

In [177]:
from imp import reload
import TEXTCNN_pytorch
reload(TEXTCNN_pytorch)

<module 'TEXTCNN_pytorch' from 'E:\\lv_python\\NLP\\阿里天池小布助手\\TEXTCNN\\TEXTCNN_pytorch.py'>

In [190]:
from TEXTCNN_pytorch import TEXTCNN

model = TEXTCNN(maxlen=maxlen,
                    max_features=max_features,
                    embedding_dims=embedding_dims,
                    class_num=class_num,
                    kernel_sizes=kernel_sizes,
                    dropout_rate=dropout_rate,
                    feature_size=feature_size,
                    vocab = corpus.v2i)

In [192]:
model.embedding.weight

Parameter containing:
tensor([[-0.0920,  0.1511, -0.1715,  ...,  0.0840,  0.0454,  0.0940],
        [ 0.0316,  0.0616, -0.2723,  ...,  0.0495,  0.1081, -0.1547],
        [-0.0801, -0.0385, -0.2032,  ..., -0.0295,  0.1278, -0.0822],
        ...,
        [-0.0310,  0.1338, -0.0175,  ..., -0.0405, -0.2103, -0.0706],
        [-0.2232,  0.0664,  0.1908,  ...,  0.1807, -0.2016,  0.0979],
        [-0.2362, -0.2368, -0.0489,  ...,  0.1335, -0.1479,  0.0074]],
       requires_grad=True)

In [111]:
import gensim
Word2vec_model = gensim.models.KeyedVectors.load_word2vec_format('./Word2Vec/Word2Vec_400.bin', binary=True)

In [115]:
import numpy as np

In [117]:
word_vocab = corpus.v2i

In [151]:
x = list(range(1, 10))
y = list(range(5, 10))
for data in x:
    z = data if data in y else None
    if z is not None:
        print(z)
    else:
        print("gg")

gg
gg
gg
gg
5
6
7
8
9


In [173]:
embedding_matrix

array([[-0.0919719 ,  0.15109034, -0.17147592, ...,  0.08398658,
         0.04537553,  0.09403314],
       [ 0.03163421,  0.0616281 , -0.2723169 , ...,  0.04948602,
         0.10811686, -0.15474498],
       [-0.08008043, -0.0385064 , -0.20319606, ..., -0.02954379,
         0.12779486, -0.08224422],
       ...,
       [ 0.14239134,  0.1760623 , -0.08992541, ...,  0.1655424 ,
         0.176705  ,  0.14613433],
       [ 0.0143168 , -0.19462781, -0.17690691, ..., -0.10978252,
        -0.11064705, -0.00087031],
       [-0.20442522, -0.05232566,  0.21068117, ..., -0.15534113,
         0.21882315,  0.08652651]])

In [164]:
cnt

20601

In [154]:
word = "245"
embedding_vector = Word2vec_model.wv[word] if word in Word2vec_model else None

In [156]:
if embedding_vector is not None:
    print(1)
else:
    print(2)

2


In [147]:
embedding_vector is not None

False

In [127]:
word in Word2vec_model

True

In [11]:
import os
os.mkdir("./Word2Vec")

In [74]:
train_loader, valid_loader, test_loader = corpus.get_loaders()

In [75]:
for batch in train_loader:
    inputs = batch[:-1]
    break

In [76]:
inputs

[tensor([[   1,   14,   63,    3,   15,  664,    0,    1,   14,  331,  664,    5,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0],
         [  94,   31, 1538,  135,  135,  164,    0, 1593,  165,   17,  177,    4,
            15,  562,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,

In [80]:
model(*inputs)

tensor([[0.4549, 0.5451],
        [0.4578, 0.5422],
        [0.4651, 0.5349],
        [0.4621, 0.5379]], grad_fn=<SoftmaxBackward>)

In [45]:
import torch.nn as nn

In [97]:
emb = nn.Embedding(num_embeddings=max_features, embedding_dim=embedding_dims)

In [98]:
emb.weight.requires_grad

True

In [61]:
model.embedding.weight.dtype

torch.float32

In [130]:
model.embedding.weight

Parameter containing:
tensor([[-0.0920,  0.1511, -0.1715,  ...,  0.0840,  0.0454,  0.0940],
        [ 0.0316,  0.0616, -0.2723,  ...,  0.0495,  0.1081, -0.1547],
        [-0.0801, -0.0385, -0.2032,  ..., -0.0295,  0.1278, -0.0822],
        ...,
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],
       requires_grad=True)

In [109]:
model.embedding_matrix

array([[-0.12898413,  0.00944187, -0.20704381, ...,  0.15879674,
         0.25146197,  0.17583833],
       [-0.24980616,  0.14945459, -0.16667096, ...,  0.05273612,
         0.19400932, -0.12150745],
       [ 0.00146409, -0.05594294,  0.05401677, ..., -0.1377127 ,
         0.06735486, -0.04046536],
       ...,
       [ 0.08236733,  0.24451374,  0.23731845, ..., -0.17505785,
         0.16749684, -0.14093859],
       [ 0.15026279, -0.1254758 , -0.04966982, ..., -0.07099763,
         0.04706879, -0.1423259 ],
       [-0.2133781 ,  0.22889107, -0.22282936, ..., -0.24597387,
         0.2347286 , -0.17734471]])

In [44]:
print(model)

TEXTCNN(
  (embedding): Embedding(20601, 400)
  (conv1ds): ModuleList(
    (0): Conv1d(400, 1024, kernel_size=(2,), stride=(1,))
    (1): Conv1d(400, 1024, kernel_size=(3,), stride=(1,))
    (2): Conv1d(400, 1024, kernel_size=(4,), stride=(1,))
    (3): Conv1d(400, 1024, kernel_size=(5,), stride=(1,))
  )
  (relu): ReLU()
  (softmax): Softmax()
  (avgpools): ModuleList(
    (0): MaxPool1d(kernel_size=90, stride=90, padding=0, dilation=1, ceil_mode=False)
    (1): MaxPool1d(kernel_size=89, stride=89, padding=0, dilation=1, ceil_mode=False)
    (2): MaxPool1d(kernel_size=88, stride=88, padding=0, dilation=1, ceil_mode=False)
    (3): MaxPool1d(kernel_size=87, stride=87, padding=0, dilation=1, ceil_mode=False)
  )
  (dropout): SpatialDropout()
  (linear): Linear(in_features=4096, out_features=512, bias=True)
  (classifier): Linear(in_features=512, out_features=2, bias=True)
)


In [64]:
import torch

In [194]:
import pandas as pd

In [202]:
data1 = pd.read_csv("../finetuned_results/2021-03-07_Linear_result.tsv", sep = ",", header = None, names = ["score"])
data2 = pd.read_csv("./finetuned_results/TextCNN_2021-03-13_result.tsv", sep = ",", header = None, names = ["score"])

In [199]:
file_path = "../finetuned_results"
filename2 = "merge_result.tsv"
import os
os.path.join(file_path, filename2)

'../finetuned_results\\merge_result.tsv'

In [204]:
file_path = "../finetuned_results"
filename2 = "merge_result.tsv"
with open(os.path.join(file_path, filename2), "w") as fw:
    for idx, (score1, score2) in enumerate(zip(data1["score"], data2["score"])):
        score = (score1 + score2)/2
        fw.write(str(score))
        if idx == len(data1) - 1:
            break
        fw.write("\n")